import React from 'react';
import Button from '@material-ui/core/Button';
import Fade from 'react-reveal/Fade';

import GraphIcon from '../../assets/Graph-Icon.svg';
import CarIcon from '../../assets/Car-Icon.svg';
import ChainIcon from '../../assets/Chain-Icon.svg';
import GoldIcon from '../../assets/Gold-Icon.svg';

import './QuickFacts.css';

const QuickFacts = (props) => {
  return (
    <div className={'quickFacts'}>
      <div className={'content'}>
        <div className={'title'}>
          DMM Assets
        </div>
        <div className={'factsList'}>
          <div className={'fact'}>
            <div className={'icon'}>
              <div className={'iconInner'}>
                <img src={GraphIcon} alt={'graph icon'}/>
              </div>
            </div>
            <div className={'factTitle'}>
              Earn consistent interest
            </div>
            <div className={'underline'}/>
            <div className={'text'}>
              Unlike most loans, DMM Assets don't fluctuate in the interest rate they pay, helping you find stability in the volatile world of crypto.
            </div>
          </div>
          <div className={'fact'}>
            <div className={'icon'}>
              <div className={'iconInner'}>
                <img src={CarIcon} alt={'car icon'}/>
              </div>
            </div>
            <div className={'factTitle'}>
              Are backed by real-world, income-generating assets
            </div>
            <div className={'underline'}/>
            <div className={'text'}>
              DMM Assets don't rely on the crypto or decentralized finance space in order to function. They bridge the real and crypto worlds.
            </div>
          </div>
          <div className={'fact'}>
            <div className={'icon'}>
              <div className={'iconInner'}>
                <img src={ChainIcon} alt={'chain icon'}/>
              </div>
            </div>
            <div className={'factTitle'}>
              Are backed by assets viewable on-chain
            </div>
            <div className={'underline'}/>
            <div className={'text'}>
              The real-world assets backing the DMM are made transparently available, bringing trust to the ecosystem.
            </div>
          </div>
          <div className={'fact gold'}>
            <div className={'icon'}>
              <div className={'iconInner'}>
                <img src={GoldIcon} alt={'gold icon'}/>
              </div>
            </div>
            <div className={'factTitle'}>
              Are always overcollateralized
            </div>
            <div className={'underline'}/>
            <div className={'text'}>
              Income generated by the underlying assets is greater than APY paid by the DMM asset.
              <br/>
              Real world assets backing DMM are always greater than DMM issued.
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default QuickFacts;
