/*eslint-disable */
import {
  h1, h2, bold, a
} from './_helper';

/*
 * Rules for translating:
 * - Only change text in quotes ("", '' or `)
 * - When you see something like h1('Welcome') ONLY change what is in the quotes
 *    - h1()        Makes text Header text (very large)
 *    - h2()        Makes text Secondary Header text (very large, not quite as large as h1)
 *    - bold()      Makes text bold
 */

export default {
  'navbar.appButton': 'APP',

  'header.mainText.first': `Earn `,
  'header.mainText.second': `6.25%`,
  'header.mainText.third': ` on ETH, DAI, USDT, and USDC with `,
  'header.mainText.fourth': `DeFi Money Market (DMM)`,
  'header.mainText.fifth': ` all backed by real world income generating assets viewable on-chain.`,
  'header.findOutHow': 'Find out how ↓',
  'header.appButton': 'Start Earning',

  'quickFacts.title': 'DMM Assets',
  'quickFacts.first.title': 'Earn consistent interest',
  'quickFacts.first.body': 'Unlike most loans, DMM Assets don\'t fluctuate in the interest rate they pay, helping you find stability in the volatile world of crypto.',
  'quickFacts.second.title': 'Are backed by real-world, income-generating assets',
  'quickFacts.second.body': 'DMM Assets don\'t rely on the crypto or decentralized finance space in order to function. They bridge the real and crypto worlds.',
  'quickFacts.third.title': 'Are backed by assets viewable on-chain',
  'quickFacts.third.body': 'The real-world assets backing the DMM are made transparently available, bringing trust to the ecosystem.',
  'quickFacts.fourth.title': 'Are always overcollateralized',
  'quickFacts.fourth.body': 'Income generated by the underlying assets is greater than APY paid by the DMM asset. Real world assets backing DMM are always greater than DMM issued.',

  'info.first.title': 'DAI, USDC, USDT or ETH are deposited in exchange for DMM mTokens.',
  'info.first.body': 'See the smart contract →',
  'info.second.title': 'The deposited DAI, USDC, USDT, and ETH are used to acquire real-world, income producing assets, all viewable on chain.',
  'info.second.body': 'Browse the assets →',
  'info.third.title': 'The assets pay out interest, which is returned to the DMM Ecosystem.',
  'info.third.body': 'See the accumulated interest →',
  'info.fourth.title': 'DMM mTokens are freely swapped back for the original DAI/USDC/USDT/ETH deposited plus interest accrued.',
  'info.fourth.body': 'Get your DMM →',

  'integrations.title.lineOne': 'Community',
  'integrations.title.lineTwo': 'Integrations',
  'integrations.button': 'Read the docs',
  'integrations.first.title': 'DMM App',
  'integrations.first.body': 'The basic app to deposit token and receive mTokens, and visa-versa.',
  'integrations.second.title': 'Integrate DMM',
  'integrations.second.body': 'Get started on your integration today.',

  'token.title.lineOne': 'DMM',
  'token.title.lineTwo': 'Tokens',
  'token.subtitle': 'Transferable. Usable. Stable.',
  'token.button': 'GET YOUR DMM',
  'token.info.first.title': 'No more gas fees',
  'token.info.first.body': 'By integrating delegated payments on the Ethereum network, users no longer have to pay gas fees in the form of ETH in order to perform transactions.',
  'token.info.second.title': 'ERC-20 Compliant',
  'token.info.second.body': 'Easily manage and transfer your DMM from any standard Ethereum wallet.',
  'token.info.third.title': 'Stable growth',
  'token.info.third.body': 'Because DMM is backed by real-world assets and a consistent interest rate, it\'s growth in value is very predictable and consistent, making it a dependable source of yield.',

  'governance.title': 'Governance',
  'governance.first.title': 'DAO Structure',
  'governance.first.body': 'The DMM Ecosystem is governed by a blockchain-based Decentralized Autonomous Organization, also known as a DAO.',
  'governance.second.title': 'Decentralized',
  'governance.second.body': 'DAO governance allows for control to be decentralized across all token holders around the world, rather than in the hands of a small few.',
  'governance.third.title': 'Community Led',
  'governance.third.body': 'Members of the ecosystem community are the ones who get to dictate the direction of the ecosystem.',
  'governance.button.dashboard': 'DAO Dashboard',
  'governance.button.learnMore': 'Learn more',

  'whitepaper.title.lineOne': 'The DMM',
  'whitepaper.title.lineTwo': 'Whitepaper',
  'whitepaper.subtitle': 'The contract. The token. The association',
  'whitepaper.button': ' READ THE WHITEPAPER',

  'partners.title': 'Partners',

  'media.title': 'In the Media',

  'team.title': 'DMM Foundation',
  'team.subtitle': 'An organization with the involvement of a unique mix of seasoned global experts in Fintech, DeFi, Venture Capital, Governance, Legal & Regulatory and Academia.',
  'team.member': 'Member',
  'team.advisor': 'Advisor',
  'team.linkedIn': 'LinkedIn',

  'investors.title': 'Investors',
  'investors.investor': 'Investor',
  'investors.wikipedia': 'Wikipedia',
  'investors.linkedIn': 'LinkedIn',

  'email.title': 'Stay up to Date',
  'email.subtitle.lineOne': 'Join our email list to receive important updates about the DMM Ecosystem.',
  'email.subtitle.lineTwo': 'Don\'t worry, we never spam or share your email!',
  'email.email': 'Email',
  'email.success': 'success',
  'email.button': 'Join',

  'footer.app': 'APP',
  'footer.docs': 'Docs',
  'footer.securityAudit': 'Security Audit',
  'footer.legal': 'Legal',
  'footer.smartContract': 'Smart Contract',
  'footer.chainlinkIntegration': 'Chainlink Integration',
  'footer.copyright': '© DeFi Money Market Foundation 2020',
  'footer.joinTheConversation': 'Join the conversation:',

  'governancePage.title': 'DMM Governance',
  'governancePage.subtitleOne': 'The DeFi Money Market (DMM) Ecosystem is governed by a global ',
  'governancePage.subtitleTwo': 'Decentralized Autonomous Organization (DAO)',
  'governancePage.subtitleThree': '.',
  'governancePage.subtitleFour': 'DAO community members dictate the direction of the ecosystem and its revenue-generating real world assets by voting with ',
  'governancePage.subtitleFive': 'DMG',
  'governancePage.subtitleSix': ', the native Governance Token of DMM.',
  'governancePage.paragraph.first.title': 'Overview',
  'governancePage.paragraph.first.body.first': 'The DMM governance token, DMG, is an ERC-20 token on the Ethereum blockchain used for the governance of the ecosystem via the DMM DAO, which can upgrade and modify the on-chain smart contracts and manage its adjacent assets.',
  'governancePage.paragraph.first.body.second': 'Ownership of DMG represents the right to govern the parameters of the DMM Protocol including the guidelines and decisions surrounding the introduction of new assets to the ecosystem in regards to both asset type and asset location.',
  'governancePage.paragraph.first.body.third': 'DMG is a fork of Compound’s COMP governance token (featuring native delegation and vote weighting) with added capability such as meta-transactions and a native burn function.',
  'governancePage.paragraph.second.title': 'DAO Voting',
  'governancePage.paragraph.second.body.first': 'The initial parameters of the DMM DAO include a 0.2% minimum quorum threshold (500k DMG), a 0.04% proposal creation threshold (100k DMG), where votes lasts three days after creation, and undergo a two day safety period for safe exits as needed.',
  'governancePage.paragraph.second.body.second': 'These parameters can be fully adjusted by the DMM DAO and evolve over time as the needs of the DMM ecosystem changes as more real world assets get brought on-chain.',
  'governancePage.paragraph.second.body.third.first': 'Current proposals and the DMM DAO dashboard can be found at ',
  'governancePage.paragraph.second.body.third.second': 'dao.defimoneymarket.com',
  'governancePage.paragraph.second.body.third.third': ' under the Vote tab, which provides full transparency into the process.',
  'governancePage.paragraph.third.title': 'Growth',
  'governancePage.paragraph.third.body.first': 'Since the DMME is overcollateralized — with real-assets yielding more than payments due to mAsset holders — the DMM DAO becomes the recipient of a positive income stream that can be used to fund further loans, capitalize related assets, burn DMG or otherwise grow the ecosystem.',
  'governancePage.paragraph.third.body.second': 'The DMM Ecosystem currently consists of $8M+ in revenue-generating real world assets, that creates a surplus for the DAO today.',
  'governancePage.paragraph.third.body.third': 'As the DMM Ecosystem grows and acquires more exposure to real world assets, the DAO will have more excess at its disposal to further grow and fund the ecosystem further.',
  'governancePage.paragraph.fourth.title': 'DAO Structure',
  'governancePage.paragraph.fourth.body.first': 'After payments are made to lenders, excess generated by the DAO will be used in accordance with how the DAO has voted, namely to grow the ecosystem and reward DMG token holders by burning DMG.',
  'governancePage.paragraph.fourth.body.second': 'As development, marketing, and maintenance of the DMM ecosystem becomes increasingly decentralized, we anticipate a portion of the DAO’s surplus will be used to pay for future protocol work and development.',
  'governancePage.conclusion': 'Through the governance structure we have laid out above and in our previous articles, it is our goal that the DMG governance token and the DMM community-operated DAO will enable DMM to become a highly decentralized protocol mitigating any potential single point of failure. We anticipate that fine-tuning this structure will be required over time and we are open to any and all feedback you may have as DMM is a community driven project first and foremost.',
  'governancePage.getStarted': 'Get started now:',
}

/*
 * Add new translations to the bottom of the file. Everytime you reconcile
 * other languages with the English.js file, add a comment saying so at the bottom
 * of the file with the date. This makes keeping track of what needs to be
 * translated much, much easier
 */
